name: Container Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container:
    name: build fedora-dev container
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build container
        run: |
          podman build \
          --format=oci \
          --tls-verify=true \
          --squash \
          --file=Containerfile \
          --tag=$GITHUB_REPOSITORY:$GITHUB_SHA \
          $GITHUB_WORKSPACE
      - name: Login to ghcr.io
        run: |
          cat #HOME/.config/containers/auth.json
          podman logout --all
          podman login --username $GITHUB_ACTOR --password ${{secrets.GITHUB_TOKEN}} ghcr.io
      - name: Push container
        run: |
          podman push $GITHUB_REPOSITORY:$GITHUB_SHA ghcr.io/$GITHUB_ACTOR/$GITHUB_REPOSITORY:latest
          podman push $GITHUB_REPOSITORY:$GITHUB_SHA ghcr.io/$GITHUB_ACTOR/$GITHUB_REPOSITORY:$GITHUB_SHA
