name: Container Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USER: kuba86
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  IMAGE_REGISTRY: docker.io

jobs:
  container:
    name: build fedora-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}
          registry: ${{ env.IMAGE_REGISTRY }}
          
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.DOCKER_USER }}/fedora-dev
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
            
      - name: Push to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
